---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app1       # Le metadata lie au deployment
spec:                         # les specifications du deployment
  replicas: 1                 # lancer un pod
  selector:    
    matchLabels:              # indiquer le pod a appliquer
      app: app-one
  template: 
    metadata:                 #ici le metadat lie au pod
      labels:                  # le label du pod  (faut etre pareil avec matchLabels)
        app: app-one  
    spec:                     #ici les specifications du pod
      containers:             # Un pod peut contenir plusieur conteneurs
        - name: app-one 
          image: nginx:stable-alpine #installer nginx pour lire le fichier index.html
          ports:
          - containerPort: 80 #port du Pod autorise (image nginx port par defaut =80 pas 8080)
          volumeMounts:       #monter un volume pointer dans le container
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:                #monter un volume pointer dans VM le chemin app1-html qui sera definir dans le script
      - name: html-volume
        configMap:
          name: app1-html 

---
# Service (pour connecter le port du pod et cluster )
apiVersion: v1
kind: Service
metadata:                     # le metadata lie au service
  name: service-app1 
spec:
  type: NodePort
  selector:
    app: app-one              #appliquer sur le pod Lable=app-one
  ports:
    - port: 80  
      protocol: TCP              # expose le service sur ce port dans le cluster, les autres pods du cluster peuvent comminiquer avec ce serveur sur ce port
      targetPort: 80        # port du Pod autorise = containerport