---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app2       # Le metadata lie au deployment
spec:                         # les specifications du deployment
  replicas: 3                 # lancer un pod
  selector:    
    matchLabels:              # indiquer le pod a appliquer
      app: app-two
  template: 
    metadata:                 #ici le metadat lie au pod
      labels:                  # le label du pod  (faut etre pareil avec matchLabels)
        app: app-two  
    spec:                     #ici les specifications du pod
      containers:             # Un pod peut contenir plusieur conteneurs
        - name: app-two 
          image: nginx:stable-alpine #installer nginx pour lire le fichier index.html
          ports:
          - containerPort: 80 #port du Pod autorise (image nginx port par defaut =80 pas 8080)
          volumeMounts:         #monter un volume pointer dans le container
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:                #monter un volume pointer vers VM le chemin app1-html qui sera definir dans le script
      - name: html-volume
        configMap:
          name: app2-html 

---
# Service (pour connecter le port du pod et cluster )
apiVersion: v1
kind: Service
metadata:                    # le metadata lie au service
  name: service-app2 
spec:  
  type: NodePort
  selector:
    app: app-two              #appliquer sur le pod Lable=app-two
  ports:
    - port: 80                # expose le service sur ce port dans le cluster, les autres pods du cluster peuvent comminiquer avec ce serveur sur ce port
      protocol: TCP
      targetPort: 80        # port du Pod autorise = containerport