apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-argocd-development
spec:
  project: development
  source:
    repoURL: https://github.com/ddalee75/iot-argocd.git
    targetRevision: HEAD                      # Branch Tracking
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc    #Accessing the Kubernetes API from a Pod 
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true