
BOX = "centos/8"
BOX_URL = "https://app.vagrantup.com/centos/boxes/8/versions/2011.0/providers/virtualbox.box"
BOX_AUTO_UPDATE = false
$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL


MASTER_NAME = "chileeS"
WORKER_NAME = "chileeSW"
MASTER_IP = "192.168.42.110"
WORKER_IP = "192.168.42.111"
LOCAL_PATH = "."
VM_PATH = "/vagrant"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_url = BOX_URL
  config.vm.box_check_update = BOX_AUTO_UPDATE
  config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT 

  config.vm.provider "virtualbox" do |vb| 
    vb.memory = "1024"
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.define MASTER_NAME do |master|
    master.vm.hostname = MASTER_NAME
    master.vm.network :private_network, ip:MASTER_IP
    master.vm.synced_folder LOCAL_PATH, VM_PATH, type: "virtualbox"
    master.vm.provision "shell", privileged: true, path: "scripts/master_setup.sh", args: [MASTER_IP]

    master.vm.provider "virtualbox" do |vb|
      vb.name = MASTER_NAME
    end
  end
 
  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network :private_network, ip:WORKER_IP
    worker.vm.synced_folder LOCAL_PATH, VM_PATH, type: "virtualbox"
    worker.vm.provision "shell", privileged: true, path: "scripts/worker_setup.sh", args:[MASTER_IP, WORKER_IP]

    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
    end
  end
end
