# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "debian/buster64"
BOX_URL = "debian/buster64"
MASTER_NAME = "gitlabVM"
MASTER_IP = "192.168.42.42"

Vagrant.configure("2") do |config|
        
    config.vm.define MASTER_NAME do |gitlab|
        gitlab.vm.network "forwarded_port", guest: 9999, host: 9999, protocol: "tcp"
        gitlab.vm.box = BOX
        gitlab.vm.box_url = BOX_URL
        gitlab.vm.hostname = MASTER_NAME
        gitlab.vm.network :private_network, ip:MASTER_IP, hostname: true

        gitlab.vm.provider "virtualbox" do |vb|
            vb.name = MASTER_NAME
            vb.memory = "4096" #(minimun 2048)
            vb.cpus = 4
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end

        gitlab.vm.provision "shell", inline: <<-SHELL
            sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
            service ssh restart #activer ssh pour ne pas dependre de vagrant ssh , pas obligatoire
        SHELL

        gitlab.vm.provision "shell", path: "scripts/install_gitlab.sh"
    end
end
