---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app3       # Le metadata lie au deployment
spec:                         # les specifications du deployment
  replicas: 1                 # lancer un pod
  selector:    
    matchLabels:              # indiquer le pod a appliquer
      app: app-three
  template: 
    metadata:                 #ici le metadat lie au pod
      labels:                  # le label du pod  (faut etre pareil avec matchLabels)
        app: app-three  
    spec:                     #ici les specifications du pod
      containers:             # Un pod peut contenir plusieur conteneurs
        - name: app-three 
          image: paulbouwer/hello-kubernetes:1.10
          imagePullPolicy: Always
          ports:
          - containerPort: 8080 #port du Pod autorise
          env:
          - name: MESSAGE
            value: "Coucou by Adrien and Ching From APP3"
---
# Service (pour connecter le port du pod et cluster )
apiVersion: v1
kind: Service
metadata:                     # le metadata lie au service
  name: service-app3 
spec:
  selector:
    app: app-three            #appliquer sur le pod Lable=app-three
  ports:
    - port: 80                # expose le service sur ce port dans le cluster, les autres pods du cluster peuvent comminiquer avec ce serveur sur ce port
      targetPort: 8080        # port du Pod autorise = containerport