apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: NodePort
  ports:
  - port: 8889
    nodePort: 30889
    targetPort: 8888
    protocol: TCP
  selector:
    app: wil-playground