
BOX = "generic/centos8"
BOX_URL = "https://app.vagrantup.com/generic/boxes/centos8/versions/3.6.12/providers/virtualbox.box"

MASTER_NAME = "chileeS"
MASTER_IP = "192.168.42.110"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_url = BOX_URL
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant"
   
  config.vm.provider "virtualbox" do |vb| 
    vb.memory = "1024"
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    #vb.gui = true
  end

  config.vm.define MASTER_NAME do |master|
    master.vm.hostname = MASTER_NAME
    master.vm.network :private_network, ip:MASTER_IP
    
    master.vm.provider "virtualbox" do |vb|
      vb.name = MASTER_NAME
    end

    master.vm.provision "shell", inline: <<-SHELL
          systemctl disable firewalld --now
			export INSTALL_K3S_EXEC="--node-ip=#{MASTER_IP} --flannel-iface=eth1 --tls-san #{MASTER_IP} --bind-address=#{MASTER_IP} --write-kubeconfig-mode 644"
      curl -sfL https://get.k3s.io |  sh -
	  echo "alias k='kubectl'" >> /etc/profile.d/00-aliases.sh 
      yum install net-tools -y
      echo "Mount volume VM Master -> container"
      /usr/local/bin/kubectl create configmap app1-html --from-file /vagrant/confs/app1/index.html
      /usr/local/bin/kubectl create configmap app2-html --from-file /vagrant/confs/app2/index.html
      /usr/local/bin/kubectl create configmap app3-html --from-file /vagrant/confs/app3/index.html
      echo " Deploying APP-1, APP-2, APP-3...."
      /usr/local/bin/kubectl apply -f  /vagrant/confs/app1.yaml
      /usr/local/bin/kubectl apply -f  /vagrant/confs/app2.yaml
      /usr/local/bin/kubectl apply -f  /vagrant/confs/app3.yaml
      /usr/local/bin/kubectl apply -f  /vagrant/confs/ingress.yaml
		SHELL
  end
end